development:
  bucket: freshboxke_dev
  access_key_id: <%= ENV['FRESHBOX_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['FRESHBOX_SECRET_ACCESS_KEY'] %>

test:
  bucket: freshboxke_test
  access_key_id: <%= ENV['FRESHBOX_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['FRESHBOX_SECRET_ACCESS_KEY'] %>

production:
  bucket: freshboxke_prod
  access_key_id: <%= ENV['FRESHBOX_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['FRESHBOX_SECRET_ACCESS_KEY'] %>
